<?php
session_start();
error_reporting(E_ALL);
ini_set('display_errors', 1);

require_once('hj2_db.php');

try {
    $songs = [
        // === POP & DANCE HITS (INTERNATIONAAL) ===
        ["artist" => "ABBA", "title" => "Dancing Queen", "year" => 1976, "theme" => "Pop"],
        ["artist" => "Madonna", "title" => "Like a Virgin", "year" => 1984, "theme" => "Pop"],
        ["artist" => "Britney Spears", "title" => "...Baby One More Time", "year" => 1998, "theme" => "Pop"],
        ["artist" => "Lady Gaga", "title" => "Bad Romance", "year" => 2009, "theme" => "Pop"],
        ["artist" => "The Weeknd", "title" => "Blinding Lights", "year" => 2019, "theme" => "Pop"],
        ["artist" => "Harry Styles", "title" => "As It Was", "year" => 2022, "theme" => "Pop"],
        ["artist" => "Kylie Minogue", "title" => "Can't Get You Out of My Head", "year" => 2001, "theme" => "Pop"],
        ["artist" => "Justin Timberlake", "title" => "Can't Stop the Feeling!", "year" => 2016, "theme" => "Pop"],
        ["artist" => "Rihanna", "title" => "Umbrella", "year" => 2007, "theme" => "Pop"],
        ["artist" => "Spice Girls", "title" => "Wannabe", "year" => 1996, "theme" => "Pop"],
        ["artist" => "Michael Jackson", "title" => "Billie Jean", "year" => 1982, "theme" => "Pop"],
        ["artist" => "Bruno Mars", "title" => "24K Magic", "year" => 2016, "theme" => "Pop"],
        ["artist" => "Dua Lipa", "title" => "Don't Start Now", "year" => 2019, "theme" => "Pop"],
        ["artist" => "Ed Sheeran", "title" => "Shape of You", "year" => 2017, "theme" => "Pop"],
        ["artist" => "Billie Eilish", "title" => "Bad Guy", "year" => 2019, "theme" => "Pop"],
        ["artist" => "Katy Perry", "title" => "Roar", "year" => 2013, "theme" => "Pop"],
        ["artist" => "Maroon 5", "title" => "Moves Like Jagger", "year" => 2011, "theme" => "Pop"],
        ["artist" => "Adele", "title" => "Rolling in the Deep", "year" => 2010, "theme" => "Pop"],
        ["artist" => "Coldplay", "title" => "A Sky Full of Stars", "year" => 2014, "theme" => "Pop"],
        ["artist" => "Justin Bieber", "title" => "Sorry", "year" => 2015, "theme" => "Pop"],
        ["artist" => "Pharrell Williams", "title" => "Happy", "year" => 2013, "theme" => "Pop"],
        ["artist" => "Sia", "title" => "Chandelier", "year" => 2014, "theme" => "Pop"],
        ["artist" => "Taylor Swift", "title" => "Shake It Off", "year" => 2014, "theme" => "Pop"],
        ["artist" => "George Michael", "title" => "Faith", "year" => 1987, "theme" => "Pop"],
        ["artist" => "Whitney Houston", "title" => "I Wanna Dance with Somebody", "year" => 1987, "theme" => "Pop"],
        ["artist" => "Cyndi Lauper", "title" => "Girls Just Want to Have Fun", "year" => 1983, "theme" => "Pop"],
        ["artist" => "Rick Astley", "title" => "Never Gonna Give You Up", "year" => 1987, "theme" => "Pop"],
        ["artist" => "Earth Wind and Fire", "title" => "September", "year" => 1978, "theme" => "Pop"],
        ["artist" => "Bee Gees", "title" => "Stayin Alive", "year" => 1977, "theme" => "Pop"],
        ["artist" => "Chaka Khan", "title" => "Ain't Nobody", "year" => 1983, "theme" => "Pop"],

        // === HONGAARSE POP & RETRO CLASSICS (SLÁGEREK) ===
        ["artist" => "Omega", "title" => "Gyöngyhajú lány", "year" => 1969, "theme" => "HU Slágerek"],
        ["artist" => "Hungária", "title" => "Csókkirály", "year" => 1980, "theme" => "HU Slágerek"],
        ["artist" => "Neoton Família", "title" => "Santa Maria", "year" => 1979, "theme" => "HU Slágerek"],
        ["artist" => "Neoton Família", "title" => "220 felett", "year" => 1981, "theme" => "HU Slágerek"],
        ["artist" => "Republic", "title" => "67-es út", "year" => 1994, "theme" => "HU Slágerek"],
        ["artist" => "Republic", "title" => "Szállj el kismadár", "year" => 1995, "theme" => "HU Slágerek"],
        ["artist" => "Edda Művek", "title" => "A kör", "year" => 1985, "theme" => "HU Slágerek"],
        ["artist" => "Edda Művek", "title" => "Kölyköd voltam", "year" => 1980, "theme" => "HU Slágerek"],
        ["artist" => "Demjén Ferenc", "title" => "Szerelem első vérig", "year" => 1985, "theme" => "HU Slágerek"],
        ["artist" => "Demjén Ferenc", "title" => "Honfoglalás", "year" => 1996, "theme" => "HU Slágerek"],
        ["artist" => "Charlie", "title" => "Jég dupla whiskyvel", "year" => 1994, "theme" => "HU Slágerek"],
        ["artist" => "Zámbó Jimmy", "title" => "Egy jó asszony mindent megbocsájt", "year" => 1992, "theme" => "HU Slágerek"],
        ["artist" => "Korda György", "title" => "Reptér", "year" => 1981, "theme" => "HU Slágerek"],
        ["artist" => "Hungária", "title" => "Hotel Menthol", "year" => 1981, "theme" => "HU Slágerek"],
        ["artist" => "Bikini", "title" => "Mielőtt elmegyek", "year" => 1987, "theme" => "HU Slágerek"],
        ["artist" => "Bikini", "title" => "Adj helyet magad mellett", "year" => 1987, "theme" => "HU Slágerek"],
        ["artist" => "R-GO", "title" => "Ballag a katona", "year" => 1984, "theme" => "HU Slágerek"],
        ["artist" => "LGT", "title" => "Neked írom a dalt", "year" => 1975, "theme" => "HU Slágerek"],
        ["artist" => "LGT", "title" => "Miénk ez a cirkusz", "year" => 1984, "theme" => "HU Slágerek"],
        ["artist" => "Rapülők", "title" => "Zúg a Volga", "year" => 1992, "theme" => "HU Slágerek"],
        ["artist" => "Rapülők", "title" => "Áj láv jú", "year" => 1993, "theme" => "HU Slágerek"],
        ["artist" => "Halott Pénz", "title" => "Valami van a levegőben", "year" => 2014, "theme" => "HU Slágerek"],
        ["artist" => "Halott Pénz", "title" => "Darabokra törted a szívem", "year" => 2015, "theme" => "HU Slágerek"],
        ["artist" => "Wellhello", "title" => "Apuved meg", "year" => 2014, "theme" => "HU Slágerek"],
        ["artist" => "Wellhello", "title" => "Rakpart", "year" => 2014, "theme" => "HU Slágerek"],
        ["artist" => "Bagossy Brothers Company", "title" => "Olyan Ő", "year" => 2019, "theme" => "HU Slágerek"],
        ["artist" => "Bagossy Brothers Company", "title" => "Visszajövök", "year" => 2020, "theme" => "HU Slágerek"],
        ["artist" => "Valmar", "title" => "Úristen", "year" => 2022, "theme" => "HU Slágerek"],
        ["artist" => "Azahriah", "title" => "Introvertált dal", "year" => 2023, "theme" => "HU Slágerek"],
        ["artist" => "Azahriah", "title" => "Rampart", "year" => 2022, "theme" => "HU Slágerek"],
        ["artist" => "Caramel", "title" => "Szállok a dallal", "year" => 2005, "theme" => "HU Slágerek"],
        ["artist" => "Magna Cum Laude", "title" => "Pálinka dal", "year" => 2009, "theme" => "HU Slágerek"],
        ["artist" => "Magna Cum Laude", "title" => "Vidéki sanzon", "year" => 2006, "theme" => "HU Slágerek"],
        ["artist" => "Quimby", "title" => "Most múlik pontosan", "year" => 2005, "theme" => "HU Slágerek"],
        ["artist" => "Quimby", "title" => "Autó egy szerpentinen", "year" => 2009, "theme" => "HU Slágerek"],
        ["artist" => "KFT", "title" => "Afrika", "year" => 1984, "theme" => "HU Slágerek"],
        ["artist" => "KFT", "title" => "Bál az Operában", "year" => 1984, "theme" => "HU Slágerek"],
        ["artist" => "Skorpió", "title" => "Azt beszéli már az egész város", "year" => 1985, "theme" => "HU Slágerek"],
        ["artist" => "Compact Disco", "title" => "Sound of Our Hearts", "year" => 2012, "theme" => "HU Slágerek"],
        ["artist" => "Punnany Massif", "title" => "Élvezd", "year" => 2013, "theme" => "HU Slágerek"],

        // === ROCK ANTHEMS (INTERNATIONAAL) ===
        ["artist" => "AC/DC", "title" => "Highway to Hell", "year" => 1979, "theme" => "Rock"],
        ["artist" => "Nirvana", "title" => "Smells Like Teen Spirit", "year" => 1991, "theme" => "Rock"],
        ["artist" => "Bon Jovi", "title" => "Livin' on a Prayer", "year" => 1986, "theme" => "Rock"],
        ["artist" => "Guns N' Roses", "title" => "Sweet Child O' Mine", "year" => 1987, "theme" => "Rock"],
        ["artist" => "Oasis", "title" => "Wonderwall", "year" => 1995, "theme" => "Rock"],
        ["artist" => "The Killers", "title" => "Mr. Brightside", "year" => 2003, "theme" => "Rock"],
        ["artist" => "Queen", "title" => "Bohemian Rhapsody", "year" => 1975, "theme" => "Rock"],
        ["artist" => "Linkin Park", "title" => "In the End", "year" => 2000, "theme" => "Rock"],
        ["artist" => "The White Stripes", "title" => "Seven Nation Army", "year" => 2003, "theme" => "Rock"],
        ["artist" => "Deep Purple", "title" => "Smoke on the Water", "year" => 1972, "theme" => "Rock"],
        ["artist" => "Led Zeppelin", "title" => "Whole Lotta Love", "year" => 1969, "theme" => "Rock"],
        ["artist" => "Pink Floyd", "title" => "Wish You Were Here", "year" => 1975, "theme" => "Rock"],
        ["artist" => "Metallica", "title" => "Nothing Else Matters", "year" => 1991, "theme" => "Rock"],
        ["artist" => "Metallica", "title" => "Enter Sandman", "year" => 1991, "theme" => "Rock"],
        ["artist" => "U2", "title" => "With or Without You", "year" => 1987, "theme" => "Rock"],
        ["artist" => "Guns N' Roses", "title" => "November Rain", "year" => 1991, "theme" => "Rock"],
        ["artist" => "Aerosmith", "title" => "Dream On", "year" => 1973, "theme" => "Rock"],
        ["artist" => "Red Hot Chili Peppers", "title" => "Californication", "year" => 1999, "theme" => "Rock"],
        ["artist" => "Red Hot Chili Peppers", "title" => "Under the Bridge", "year" => 1991, "theme" => "Rock"],
        ["artist" => "Foo Fighters", "title" => "Everlong", "year" => 1997, "theme" => "Rock"],
        ["artist" => "Green Day", "title" => "Basket Case", "year" => 1994, "theme" => "Rock"],
        ["artist" => "Green Day", "title" => "Boulevard of Broken Dreams", "year" => 2004, "theme" => "Rock"],
        ["artist" => "Radiohead", "title" => "Creep", "year" => 1992, "theme" => "Rock"],
        ["artist" => "Evanescence", "title" => "Bring Me to Life", "year" => 2003, "theme" => "Rock"],
		["artist" => "Kings of Leon", "title" => "Use Somebody", "year" => 2008, "theme" => "Rock"],
		["artist" => "The Cranberries", "title" => "Zombie", "year" => 1994, "theme" => "Rock"],
		["artist" => "R.E.M.", "title" => "Losing My Religion", "year" => 1991, "theme" => "Rock"],
		["artist" => "Lenny Kravitz", "title" => "Are You Gonna Go My Way", "year" => 1993, "theme" => "Rock"],
		["artist" => "Joan Jett", "title" => "I Love Rock 'N Roll", "year" => 1981, "theme" => "Rock"],
		["artist" => "The Police", "title" => "Every Breath You Take", "year" => 1983, "theme" => "Rock"],
		["artist" => "Dire Straits", "title" => "Sultans of Swing", "year" => 1978, "theme" => "Rock"],
		["artist" => "Toto", "title" => "Africa", "year" => 1982, "theme" => "Rock"],
		["artist" => "Bryan Adams", "title" => "Summer of '69", "year" => 1984, "theme" => "Rock"],
		["artist" => "Bruce Springsteen", "title" => "Born in the U.S.A.", "year" => 1984, "theme" => "Rock"],
		["artist" => "David Bowie", "title" => "Heroes", "year" => 1977, "theme" => "Rock"],
		        // === FILM & CINEMA HITS ===
        ["artist" => "Celine Dion", "title" => "My Heart Will Go On", "year" => 1997, "theme" => "Film"],
        ["artist" => "Survivor", "title" => "Eye of the Tiger", "year" => 1982, "theme" => "Film"],
        ["artist" => "Ray Parker Jr.", "title" => "Ghostbusters", "year" => 1984, "theme" => "Film"],
        ["artist" => "Whitney Houston", "title" => "I Will Always Love You", "year" => 1992, "theme" => "Film"],
        ["artist" => "Kenny Loggins", "title" => "Footloose", "year" => 1984, "theme" => "Film"],
        ["artist" => "John Williams", "title" => "Star Wars Main Title", "year" => 1977, "theme" => "Film"],
        ["artist" => "Hans Zimmer", "title" => "He's a Pirate", "year" => 2003, "theme" => "Film"],
        ["artist" => "Bill Medley", "title" => "(I'Had) The Time of My Life", "year" => 1987, "theme" => "Film"],
        ["artist" => "Roy Orbison", "title" => "Oh, Pretty Woman", "year" => 1964, "theme" => "Film"],
        ["artist" => "Pharrell Williams", "title" => "Happy", "year" => 2013, "theme" => "Film"],
        ["artist" => "Los Del Rio", "title" => "Macarena", "year" => 1993, "theme" => "Film"],
        ["artist" => "Aqua", "title" => "Barbie Girl", "year" => 1997, "theme" => "Film"],
        ["artist" => "Psy", "title" => "Gangnam Style", "year" => 2012, "theme" => "Film"],
        ["artist" => "Coolio", "title" => "Gangsta's Paradise", "year" => 1995, "theme" => "Film"],
        ["artist" => "Eminem", "title" => "Lose Yourself", "year" => 2002, "theme" => "Film"],
        ["artist" => "Bee Gees", "title" => "Night Fever", "year" => 1977, "theme" => "Film"],
        ["artist" => "John Travolta and Olivia Newton-John", "title" => "You're the One That I Want", "year" => 1978, "theme" => "Film"],
        ["artist" => "Steppenwolf", "title" => "Born to Be Wild", "year" => 1968, "theme" => "Film"],
        ["artist" => "Simple Minds", "title" => "Don't You (Forget About Me)", "year" => 1985, "theme" => "Film"],
        ["artist" => "The Blues Brothers", "title" => "Everybody Needs Somebody to Love", "year" => 1980, "theme" => "Film"],
        ["artist" => "Seal", "title" => "Kiss from a Rose", "year" => 1994, "theme" => "Film"],
        ["artist" => "Huey Lewis and The News", "title" => "The Power of Love", "year" => 1985, "theme" => "Film"],
        ["artist" => "Adele", "title" => "Skyfall", "year" => 2012, "theme" => "Film"],
        ["artist" => "Will Smith", "title" => "Men in Black", "year" => 1997, "theme" => "Film"],
        ["artist" => "Dick Dale", "title" => "Misirlou", "year" => 1962, "theme" => "Film"],
        ["artist" => "The Beatles", "title" => "A Hard Day's Night", "year" => 1964, "theme" => "Film"],
        ["artist" => "The Beach Boys", "title" => "Kokomo", "year" => 1988, "theme" => "Film"],
        ["artist" => "Simon and Garfunkel", "title" => "Mrs. Robinson", "year" => 1968, "theme" => "Film"],
        ["artist" => "Idina Menzel", "title" => "Let It Go", "year" => 2013, "theme" => "Film"],
        ["artist" => "Lady Gaga and Bradley Cooper", "title" => "Shallow", "year" => 2018, "theme" => "Film"],

        // === SOUL, R&B & OLDIES (1960 - 1980) ===
        ["artist" => "The Beatles", "title" => "Hey Jude", "year" => 1968, "theme" => "Oldies"],
        ["artist" => "The Rolling Stones", "title" => "(I Can't Get No) Satisfaction", "year" => 1965, "theme" => "Oldies"],
        ["artist" => "Elvis Presley", "title" => "Suspicious Minds", "year" => 1969, "theme" => "Oldies"],
        ["artist" => "Fleetwood Mac", "title" => "Go Your Own Way", "year" => 1977, "theme" => "Oldies"],
        ["artist" => "Bob Marley and The Wailers", "title" => "Three Little Birds", "year" => 1977, "theme" => "Oldies"],
        ["artist" => "Stevie Wonder", "title" => "Superstition", "year" => 1972, "theme" => "Oldies"],
        ["artist" => "Marvin Gaye", "title" => "What's Going On", "year" => 1971, "theme" => "Oldies"],
        ["artist" => "Creedence Clearwater Revival", "title" => "Bad Moon Rising", "year" => 1969, "theme" => "Oldies"],
        ["artist" => "The Beach Boys", "title" => "Good Vibrations", "year" => 1966, "theme" => "Oldies"],
        ["artist" => "Bill Withers", "title" => "Ain't No Sunshine", "year" => 1971, "theme" => "Oldies"],
        ["artist" => "Aretha Franklin", "title" => "Respect", "year" => 1967, "theme" => "Oldies"],
        ["artist" => "James Brown", "title" => "I Got You (I Feel Good)", "year" => 1965, "theme" => "Oldies"],
        ["artist" => "The Temptations", "title" => "My Girl", "year" => 1964, "theme" => "Oldies"],
        ["artist" => "The Supremes", "title" => "Baby Love", "year" => 1964, "theme" => "Oldies"],
        ["artist" => "The Jimi Hendrix Experience", "title" => "All Along the Watchtower", "year" => 1968, "theme" => "Oldies"],
        ["artist" => "The Doors", "title" => "Light My Fire", "year" => 1967, "theme" => "Oldies"],
        ["artist" => "The Kinks", "title" => "You Really Got Me", "year" => 1964, "theme" => "Oldies"],
        ["artist" => "The Who", "title" => "My Generation", "year" => 1965, "theme" => "Oldies"],
        ["artist" => "Simon and Garfunkel", "title" => "The Sound of Silence", "year" => 1965, "theme" => "Oldies"],
        ["artist" => "Van Morrison", "title" => "Brown Eyed Girl", "year" => 1967, "theme" => "Oldies"],
        ["artist" => "Otis Redding", "title" => "(Sittin' On) The Dock of the Bay", "year" => 1968, "theme" => "Oldies"],
        ["artist" => "The Monkees", "title" => "I'm a Believer", "year" => 1966, "theme" => "Oldies"],
        ["artist" => "Johnny Cash", "title" => "Ring of Fire", "year" => 1963, "theme" => "Oldies"],
        ["artist" => "Bob Dylan", "title" => "Like a Rolling Stone", "year" => 1965, "theme" => "Oldies"],
        ["artist" => "Neil Diamond", "title" => "Sweet Caroline", "year" => 1969, "theme" => "Oldies"],
        ["artist" => "The Jackson 5", "title" => "I Want You Back", "year" => 1969, "theme" => "Oldies"],
        ["artist" => "Elton John", "title" => "Your Song", "year" => 1970, "theme" => "Oldies"],
        ["artist" => "Rod Stewart", "title" => "Maggie May", "year" => 1971, "theme" => "Oldies"],
        ["artist" => "John Lennon", "title" => "Imagine", "year" => 1971, "theme" => "Oldies"],
        ["artist" => "Bill Withers", "title" => "Lean on Me", "year" => 1972, "theme" => "Oldies"],
        ["artist" => "The Eagles", "title" => "Hotel California", "year" => 1976, "theme" => "Oldies"],
        ["artist" => "Fleetwood Mac", "title" => "Dreams", "year" => 1977, "theme" => "Oldies"],
        ["artist" => "Electric Light Orchestra", "title" => "Mr. Blue Sky", "year" => 1977, "theme" => "Oldies"],
        ["artist" => "Donna Summer", "title" => "I Feel Love", "year" => 1977, "theme" => "Oldies"],
        ["artist" => "Gloria Gaynor", "title" => "I Will Survive", "year" => 1978, "theme" => "Oldies"],
        ["artist" => "The Police", "title" => "Roxanne", "year" => 1978, "theme" => "Oldies"],
        ["artist" => "Michael Jackson", "title" => "Don't Stop 'Til You Get Enough", "year" => 1979, "theme" => "Oldies"],
        ["artist" => "Pink Floyd", "title" => "Another Brick in the Wall, Pt. 2", "year" => 1979, "theme" => "Oldies"],

        // === DANCE, ELECTRONIC & HIP-HOP ANTHEMS ===
        ["artist" => "Dr. Dre", "title" => "Still D.R.E.", "year" => 1999, "theme" => "Dance & Urban"],
        ["artist" => "Outkast", "title" => "Hey Ya!", "year" => 2003, "theme" => "Dance & Urban"],
        ["artist" => "50 Cent", "title" => "In Da Club", "year" => 2003, "theme" => "Dance & Urban"],
        ["artist" => "Usher", "title" => "Yeah!", "year" => 2004, "theme" => "Dance & Urban"],
        ["artist" => "Alicia Keys", "title" => "If I Ain't Got You", "year" => 2003, "theme" => "Dance & Urban"],
        ["artist" => "The Black Eyed Peas", "title" => "I Gotta Feeling", "year" => 2009, "theme" => "Dance & Urban"],
        ["artist" => "Beyoncé", "title" => "Single Ladies (Put a Ring on It)", "year" => 2008, "theme" => "Dance & Urban"],
        ["artist" => "Jay-Z", "title" => "Empire State of Mind", "year" => 2009, "theme" => "Dance & Urban"],
        ["artist" => "Snoop Dogg", "title" => "Drop It Like It's Hot", "year" => 2004, "theme" => "Dance & Urban"],
        ["artist" => "Daft Punk", "title" => "Around the World", "year" => 1997, "theme" => "Dance & Urban"],
        ["artist" => "Daft Punk", "title" => "Get Lucky", "year" => 2013, "theme" => "Dance & Urban"],
        ["artist" => "The Prodigy", "title" => "Firestarter", "year" => 1996, "theme" => "Dance & Urban"],
        ["artist" => "Faithless", "title" => "Insomnia", "year" => 1995, "theme" => "Dance & Urban"],
        ["artist" => "Avicii", "title" => "Wake Me Up", "year" => 2013, "theme" => "Dance & Urban"],
        ["artist" => "Avicii", "title" => "Levels", "year" => 2011, "theme" => "Dance & Urban"],
        ["artist" => "Swedish House Mafia", "title" => "Don't You Worry Child", "year" => 2012, "theme" => "Dance & Urban"],
        ["artist" => "Calvin Harris", "title" => "Summer", "year" => 2014, "theme" => "Dance & Urban"],
        ["artist" => "David Guetta", "title" => "Titanium", "year" => 2011, "theme" => "Dance & Urban"],
        ["artist" => "Tiësto", "title" => "Adagio for Strings", "year" => 2004, "theme" => "Dance & Urban"],
        ["artist" => "Armin van Buuren", "title" => "This Is What It Feels Like", "year" => 2013, "theme" => "Dance & Urban"],
        ["artist" => "Fatboy Slim", "title" => "Praise You", "year" => 1998, "theme" => "Dance & Urban"],
        ["artist" => "Chemical Brothers", "title" => "Galvanize", "year" => 2005, "theme" => "Dance & Urban"],
        ["artist" => "Macklemore and Ryan Lewis", "title" => "Thrift Shop", "year" => 2012, "theme" => "Dance & Urban"],
        ["artist" => "Kanye West", "title" => "Gold Digger", "year" => 2005, "theme" => "Dance & Urban"],
		["artist" => "Gorillaz", "title" => "Feel Good Inc.", "year" => 2005, "theme" => "Dance & Urban"],
		["artist" => "Gnarls Barkley", "title" => "Crazy", "year" => 2006, "theme" => "Dance & Urban"],
		["artist" => "Amy Winehouse", "title" => "Rehab", "year" => 2006, "theme" => "Dance & Urban"],
		["artist" => "Bruno Mars", "title" => "Uptown Funk", "year" => 2014, "theme" => "Dance & Urban"],
		["artist" => "LMFAO", "title" => "Party Rock Anthem", "year" => 2011, "theme" => "Dance & Urban"],
		["artist" => "Gigi D'Agostino", "title" => "L'Amour Toujours", "year" => 1999, "theme" => "Dance & Urban"],
		["artist" => "Darude", "title" => "Sandstorm", "year" => 1999, "theme" => "Dance & Urban"],
		["artist" => "Stromae", "title" => "Alors on danse", "year" => 2009, "theme" => "Dance & Urban"]
	];
	
	$checkStmt = $db->prepare("SELECT COUNT(*) FROM game_songs WHERE artist = ? AND title = ?");
    $insertStmt = $db->prepare("INSERT INTO game_songs (artist, title, year, theme) VALUES (?, ?, ?, ?)");

    $toegevoegd = 0;
    $overgeslagen = 0;

    foreach ($songs as $song) {
        $checkStmt->execute([$song['artist'], $song['title']]);
        if ($checkStmt->fetchColumn() == 0) {
            $insertStmt->execute([$song['artist'], $song['title'], $song['year'], $song['theme']]);
            $toegevoegd++;
        } else {
            $overgeslagen++;
        }
    }

    echo "<div style='font-family:sans-serif; text-align:center; padding:20px; color:white; background:#28a745; max-width:400px; margin:40px auto; border-radius:10px;'>";
    echo "<h3>🎉 Import Klaar!</h3>";
    echo "<p>Toegevoegd: <strong>$toegevoegd</strong></p>";
    echo "<p>Overgeslagen: <strong>$overgeslagen</strong></p>";
    echo "</div>";

} catch (Exception $e) {
    die("<p style='color:red;'>❌ Fout tijdens importeren: " . $e->getMessage() . "</p>");
}
?>