

services:
  webserver:
    container_name: HitJam4
    image: hitjam4-app
    ports:
      - "8088:80"
    volumes:
      - .:/var/www/html
      - ./HitData:/var/www/html/HitData
    restart: always
